---
title: Analyse peak response
format:
  html:
    embed-resources: true
---

```{r}
#| include: false
library(ggplot2)
library(tibble)
```


## Data prep

Here we load the data:

```{r}
library(DataTidy24TBVaccSexDiff)
data("data_tidy_vacc_freq")
```

Here we extract the peak response:

```{r}
data_tidy_vacc_peak <- data_tidy_vacc_freq |>
  vacc_extract_peak()
data_tidy_vacc_peak
```

Now we calculate the summed response and the peak response:

```{r}
data_tidy_vacc_summed <- data_tidy_vacc_peak |>
  vacc_calc_response_summed("response") |>
  #vacc_calc_vaccine_induced_response(cn_resp = "response") |>
  vacc_set_neg_to_zero("response") |>
  dplyr::filter(subset == "cd4")
data_tidy_vacc_summed
data_tidy_vacc_profile <- data_tidy_vacc_peak |>
  vacc_calc_response_profile("response") |>
  #vacc_calc_vaccine_induced_response(cn_resp = "response") |>
  dplyr::filter(subset == "cd4")
data_tidy_vacc_profile
```

## Analysis

Kruskal-Wallis Test:

```{r}
vacc_inf_sex <- with(data_tidy_vacc_summed, interaction(vaccine, infxn, sex))
test <- kruskal.test(response ~ vacc_inf_sex, data = data_tidy_vacc_summed)
test
```

Skewness of Responses:

```{r}
#install.packages('moments')
library(moments)
skewness(data_tidy_vacc_summed$response)

png(file="histogram.png")
hist(data_tidy_vacc_summed$response, col='blue')
dev.off()
```

Load betareg package:

```{r}
#install.packages('betareg')
#install.packages('statmod')
#install.packages("numDeriv")
library(betareg)
```

Transform response to lie between 0 and 1:

```{r}
data_tidy_vacc_summed$response <- data_tidy_vacc_summed$response / max(data_tidy_vacc_summed$response)
```

Fit a Beta Regression Model:

```{r}
betaregunin_model <- betareg(response ~ sex*vaccine, data = data_tidy_vacc_summed|> dplyr::filter(infxn == "uninfected"))
summary(betaregunin_model)

png(file="beta residuals.png")
plot(residuals(betaregunin_model), type = "p",col='red')
dev.off()

betaregin_model <- betareg(response ~ sex*vaccine, data = data_tidy_vacc_summed|> dplyr::filter(infxn == "infected"))
summary(betaregin_model)
```

```{r}
data_tidy_vacc_summed_inf <- data_tidy_vacc_summed |>  dplyr::filter(infxn == "infected") 
betaregin_model_h1 <- betareg(  response ~ sex,  data = data_tidy_vacc_summed_inf |>    dplyr::filter(vaccine == "h1")) 
betaregin_model_h56 <- betareg(  response ~ sex,  data = data_tidy_vacc_summed_inf |>    dplyr::filter(vaccine == "h56")) 
betaregin_model_mva85a <- betareg(  response ~ sex,  data = data_tidy_vacc_summed_inf |>    dplyr::filter(vaccine == "mva85a"))

p_vec <- c(
  summary(betaregin_model_h1)$coefficients$mean[2, 4],
  summary(betaregin_model_h56)$coefficients$mean[2, 4],
  summary(betaregin_model_mva85a)$coefficients$mean[2, 4]
)
p_vec

p.adjust(p_vec, method = "holm")
```

Load gamlss package:

```{r}
#install.packages('gamlss')
library(gamlss)
```

Fit Gamlss model:

```{r}
data_tidy_vacc_summed$response <- pmin(pmax(data_tidy_vacc_summed$response, .Machine$double.eps), 1 - .Machine$double.eps)

gamlss_model1 <- gamlss(response ~ vaccine + infxn + sex + subset, data = data_tidy_vacc_summed)
summary(gamlss_model1)

png(file="gamlss residuals 1.png")
plot(residuals(gamlss_model1), type = "p",col='red')
dev.off()

gamlss_model2 <- gamlss(response ~ vaccine + infxn + sex + subset, 
                sigma.formula = ~ vaccine + infxn + sex + subset, 
                family = BE(), data = data_tidy_vacc_summed)
summary(gamlss_model2)

png(file="gamlss residuals 2.png")
plot(residuals(gamlss_model2), type = "p",col='red')
dev.off()
```

